language: node_js
node_js:
  - '12'
install: npm install
script:
  - npm run build
  - docker build -t teamwork .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag teamwork jinminrui/teamwork
  - docker push jinminrui/teamwork
