export const SET_PROJECT_LIST = 'SET_PROJECT_LIST';
export const SET_LIST_LOADING = 'SET_LIST_LOADING';
export const SET_PROJECT_MEMBERS = 'SET_PROJECT_MEMBERS';
export const SET_PROJECT_DETAIL = 'SET_PROJECT_DETAIL';

/**
 * SAGA
 */
export const GET_PROJECT_LIST_SAGA = 'GET_PROJECT_LIST_SAGA';
export const GET_PROJECT_MEMBERS_SAGA = 'GET_PROJECT_MEMBERS_SAGA';
export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';
