export const CONNECT_WEBSOCKET = 'CONNECT_WEBSOCKET';
export const DISCONNECT_WEBSOCKET = 'DISCONNECT_WEBSOCKET';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SET_TOTAL = 'SET_TOTAL';
export const SET_NOT_READ = 'SET_NOT_READ';
export const GET_REVEIVED_MESSAGE_LIST_SAGE = 'GET_REVEIVED_MESSAGE_LIST_SAGE';
export const SET_REVEIVED_MESSAGE_LIST = 'SET_REVEIVED_MESSAGE_LIST';
