export const SET_CLASS_INFO = 'SET_CLASS_INFO';
export const SET_CREATE_TASK_PROPS = 'SET_CREATE_TASK_PROPS';
export const SET_VIEW_TASK_PROPS = 'SET_VIEW_TASK_PROPS';
export const SET_CLASS_INFO_LOADING = 'SET_CLASS_INFO_LOADING';
export const SET_TASK_LIST_LOADING = 'SET_TASK_LOADING';
export const SET_TASK_LIST = 'SET_TASK_LIST';
export const SET_SPRINT_LIST = 'SET_SPRINT_LIST';

export const GET_CLASS_INFO_SAGA = 'GET_CLASS_INFO_SAGA';
export const GET_TASK_LIST_SAGA = 'GET_TASK_LIST_SAGA';
export const GET_SPRINT_LIST_SAGA = 'GET_SPRINT_LIST_SAGA';
